INSERT INTO Majors(MajorID,MajorName) VALUES
 ('M1','Computer Science & Information Technology')
,('M2','Engineering Technology')
,('M3','Business Management & Leadership')
,('M4','Environmental Science & Sustainable Development')
,('M5','Mathematics & Statistical Analysis')
,('M6','Social Sciences & Cultural Studies')
,('M7','Humanities & Critical Thought')
,('M8','Visual and Performing Arts')
,('M9','Health Sciences & Medicine')
,('M10','Language')
,('M11','Literature & Cultural Studies')
,('M12','Advanced Computing & Digital Technologies')
,('M13','Specialized Engineering and Technology')
,('M14','Progressive Business & Finance')
,('M15','Advanced Environmental Studies')
,('M16','Higher Mathematics & Theoretical Studies')
,('M17','In-Depth Social Sciences & Humanities')
,('M18','Advanced Arts')
,('M19','Design & Multimedia')
,('M20','Advanced Health Sciences & Medicine')
,('M21','Language Mastery & Intercultural Communication')
,('M22','Special Topics & Innovative Fields')
,('M23','Artificial Intelligence & Robotics')
,('M24','Biotechnology & Bioengineering')
,('M25','Marketing & Advertising')
,('M26','Global Studies & International Relations')
,('M27','Physics & Astronomy')
,('M28','Psychology & Behavioral Sciences')
,('M29','Philosophy & Ethics')
,('M30','Music & Music Technology')
,('M31','Nursing & Public Health')
,('M32','Modern Languages & Global Communication')
,('M33','Cybersecurity & Information Assurance')
,('M34','Electrical & Electronics Engineering')
,('M35','Entrepreneurship & Venture Management')
,('M36','Earth Sciences & Geology')
,('M37','Actuarial Science & Risk Management')
,('M38','Political Science & Government')
,('M39','Fine Arts & Art History')
,('M40','Medical Sciences & Clinical Research')
,('M41','Linguistics & Language Theory')
,('M42','Data Science & Big Data Analytics')
,('M43','Chemical & Process Engineering')
,('M44','Human Resource Management')
,('M45','Ecology & Conservation Biology')
,('M46','Applied Mathematics & Computational Science')
,('M47','Sociology & Community Development')
,('M48','Religious Studies & Theology')
,('M49','Theatre & Performance Studies')
,('M50','Allied Health Professions')
,('M51','Translation & Interpretive Studies')
,('M52','Aerospace & Aeronautical Engineering')
,('M53','Finance & Investment')
,('M54','Chemistry & Chemical Sciences')
,('M55','Cognitive Science & Neuropsychology')
,('M56','Classical Studies & Ancient History')
,('M57','Dance & Choreography')
,('M58','Dental & Oral Sciences')
,('M59','Asian Studies & Eastern Philosophy')
,('M60','Mechanical & Industrial Engineering')
,('M61','International Business & Trade')
,('M62','Meteorology & Atmospheric Sciences')
,('M63','Forensic Science & Criminal Justice')
,('M64','Archaeology & Paleontology')
,('M65','Drama')
,('M66','Film & Media Studies')
,('M67','Optometry & Vision Sciences')
,('M68','Middle Eastern Studies & Arabic Language')
,('M69','Automotive Engineering & Mobility')
,('M70','Real Estate & Urban Economics')
,('M71','Marine Biology & Oceanography')
,('M72','Nutrition & Food Science')
,('M73','Gender Studies & Sexuality')
,('M74','Animation & Game Design')
,('M75','Paramedical Sciences')
,('M76','Russian & Slavic Studies')
,('M77','Agricultural Sciences & Agribusiness')
,('M78','Energy Studies & Management')
,('M79','Materials Science & Engineering')
,('M80','International Development & Humanitarian Aid')
,('M81','Sports Science & Kinesiology')
,('M82','Italian Studies & Romance Languages')
,('M83','Urban Planning & Public Policy')
,('M84','Veterinary Sciences & Animal Health')
,('M85','Military Science & National Security')
,('M86','Astrophysics & Space Science')
,('M87','Fashion Design & Merchandising')
,('M88','Pharmacology & Pharmaceutical Sciences')
,('M89','Scandinavian Culture & Languages')
,('M90','Civil & Environmental Engineering')
,('M91','Accounting & Financial Reporting')
,('M92','Biochemistry & Molecular Biology')
,('M93','Anthropology & Ethnography')
,('M94','Creative Writing & Literature')
,('M95','Gerontology & Aging Studies')
,('M96','Southeast Asian & Pacific Studies')
,('M97','Graphic Design & Visual Communication')
,('M98','Hospitality & Tourism Management')
,('M99','Public Administration & Civic Engagement')
,('M100','Physical Therapy & Rehabilitation Sciences');
